# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: ninr_resnet200_cifar10_32-64-4layer-200e-large-res-coordnoise99
  num_epochs: 200
  log_interval: 50
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: None

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 64
  coordinate_noise: 1.0
  # strong_aug: v1
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar100_32-64-4layer-200elarge-res-coordnoise99 # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  hidden_dim: 512
  num_layers: 8
  num_freqs: 32
  output_dim: 9
  ema_decay: 0.99  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
