# Experiment settings
# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: ninr_resnet20_cifar100_32-160-4layer-400e-coordnoise-bs128-400e
  num_epochs: 200
  log_interval: 100
  eval_interval: 5
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: None

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 1.0
  # strong_aug: v1
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar100_32-160-4layer-400e-coordnoise-bs128-400e # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  input_dim: 6
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32, 160]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
