# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: ninr_resnet200_cifar10_32-64-4layer-400e-large-res-coordnoise
  num_epochs: 400
  log_interval: 100
  eval_interval: 5
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: toy/checkpoint/cifar100_ResNet20_smoothed.pth

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 1.0
  lr_steps: [200, 300]
  # strong_aug: v1
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar100_32-64-4layer-400elarge-res-coordnoise # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  hidden_dim: 512
  num_layers: 8
  num_freqs: 32
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
