# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: ninr_resnet32_cifar100_32-64-4layer-200e-large-res-coordnoise
  num_epochs: 200
  log_interval: 100
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet32
  pretrained_path: None

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 1.0
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet32_cifar100_32-64-4layer-200elarge-res-coordnoise # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  hidden_dim: 256
  num_layers: 8
  num_freqs: 32
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay
  loss_weight:
    ce_weight: 1.0
    reg_weight: 0.0
    recon_weight: 0.0
    kd_weight: 0.1


# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
