model:
  name: "unet"
  num_classes: 21
  encoder_name: "resnet18"
  encoder_weights: "imagenet"
  in_channels: 3

training:
  strong_aug: True
  max_iterations: 40000
  eval_every: 4000
  log_every: 100
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  grad_clip: 5.0
  checkpoint_path: toy/checkpoint/unet_r18_voc_checkpoint.pth.tar
  checkpoint_dir: ./toy/experiments/unet_r18_voc_original_strong  # Add your checkpoint directory here

dataset:
  root: "/local_home/yangxingyi/dataset/VOCdevkit"
  year_train: "2012_aug"
  image_set_train: "train"
  year_val: "2012"
  image_set_val: "val"
  batch_size_train: 8
  batch_size_val: 1
  num_workers_train: 12
  num_workers_val: 4

transforms:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  resize: [480, 640]
  random_crop: 512
  flip_prob: 0.5

wandb:
  project: "segmentation"
