# Experiment settings
experiment:
  name: ninr_resnet20_cifar10_32-64-4layer-5
  recononly: 0
  num_epochs: 30
  log_interval: 25
  eval_interval: 1
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: resnet20-12fca82f.th  # Path to pre-trained model
  smooth: False

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 64
  coordinate_noise: 0.0
  lr_steps: [100, 150]
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar10_32-64-4layer-5 # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  input_dim: 6
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

  loss_weight:
    ce_weight: 1.0
    reg_weight: 0.0001
    recon_weight: 1.0
    kd_weight: 0.1

# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
