# Experiment settings
experiment:
  name: ninr_resnet18_imageney-500-512
  num_epochs: 30
  log_interval: 1
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet18
  pretrained_path: None  # Path to pre-trained model

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 64
  data_path: /local_home/fanggongfan/Datasets/ImageNet/
  # strong_aug: v1
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet18_imageney-500-512 # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  input_dim: 6
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [512]  # Dimension range for the experiment
  test: 512  # Testing dimension
  norm: 512  # Normalization factor
  start: 512  # Starting dimension
