# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: ninr_resnet20_cifar10_32-96-4layer-200e-noisecoord-128bs
  num_epochs: 200
  log_interval: 100
  eval_interval: 5
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: resnet20-12fca82f.th  # Path to pre-trained model

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 1.0
  lr_steps: [100, 150]
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar10_32-96-4layer-200e-noisecoord-128bs # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  input_dim: 6
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32, 96]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
