# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: fashionmnist_lenet_8-32-noise-largerres0-recon1.0
  num_epochs: 400
  log_interval: 100
  eval_interval: 5
  seed: 42  # Random seed

# Model configurations
model:
  type: LeNet
  pretrained_path: toy/fashionmnist_MnistNet_dim32.pth

# Training configurations
training:
  dataset: fashionmnist
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 1.0
  lr_steps: [200, 300]
  # strong_aug: v1
  weight_decay: 0.0
  clip_grad: 0.0
  save_model_path: toy/experiments/fashionmnist_lenet_8-32-noise-largerres0-recon1.0/ # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  scalar: 0.0
  input_dim: 6
  hidden_dim: 256
  num_layers: 12
  num_freqs: 16
  output_dim: 25
  ema_decay: 0.995  # Exponential moving average decay

  loss_weight:
    ce_weight: 1.0
    reg_weight: 0.0001
    recon_weight: 1.0
    kd_weight: 0.1

# Experiment dimensions configuration
dimensions:
  range: [8, 32]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 32  # Normalization factor
  start: 32  # Starting dimension
