# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: mnist_lenet_32
  num_epochs: 30
  log_interval: 50
  seed: 42  # Random seed

# Model configurations
model:
  type: LeNet
  pretrained_path: toy/mnist_MnistNet_dim32.pth

# Training configurations
training:
  dataset: mnist
  learning_rate: 1e-3
  batch_size: 128
  # strong_aug: v1
  weight_decay: 0.0
  clip_grad: 0.0
  save_model_path: toy/experiments/mnist_lenet_32/ # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 25
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 32  # Normalization factor
  start: 32  # Starting dimension
