# Experiment settings
base_config: toy/experiments/base_config.yaml

experiment:
  name: mnist_resnet_width8-16
  num_epochs: 50
  log_interval: 50
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet_width
  pretrained_path: toy/mnist_MnistResNet_dim16_permute.pth

# Training configurations
training:
  dataset: mnist
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 0.0
  # strong_aug: v1
  weight_decay: 0.0
  clip_grad: 5.0
  save_model_path: toy/experiments/mnist_resnet_width8-16/ # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  scalar: 0.0
  hidden_dim: 256
  num_layers: 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay
  loss_weight:
    ce_weight: 0.0
    reg_weight: 0.0
    recon_weight: 100.0
    kd_weight: 0.1

# Experiment dimensions configuration
dimensions:
  range: [16]  # Dimension range for the experiment
  test: 16  # Testing dimension
  norm: 16  # Normalization factor
  start: 16  # Starting dimension
